import "~/styles/globals.css";
import { TRPCReactProvider } from "~/trpc/react";
import { ClerkProvider } from "@clerk/nextjs";
import { SessionProvider } from "~/components";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <TRPCReactProvider>
      <html>
        <body>
          <ClerkProvider>
            <SessionProvider>{children}</SessionProvider>
          </ClerkProvider>
        </body>
      </html>
    </TRPCReactProvider>
  );
}
